files {
    'loading.html',
    'config.js',
    'script.js',
    'style.css',
    'live.ogg',
    'icon/crown.png',
    'icon/discord.png',
    'icon/facebook.png',
    'icon/music.png',
    'icon/person.png',
    'icon/tip.png',
    'icon/twitch.png',
    'icon/twitter.png',
    'icon/vulkanoa.png',
    'icon/youtube.png',
	'icon/website.png',
    'img/1.jpg',
    'img/2.jpg',
    'img/3.jpg',
	'img/4.jpg',
	'img/5.png',
	'img/6.jpg',
	'img/7.jpg',
	'img/8.jpg',
	'img/9.jpg',
	'img/10.jpg',
}

loadscreen 'loading.html'